security:
    # Le chemin vers votre encodeur de mot de passe
    password_hashers:
        App\Entity\Client:
            algorithm: 'auto' # Utilise l'algorithme recommandé par Symfony

    # Configuration du fournisseur d'utilisateurs
    providers:
        app_client_provider:
            entity:
                class: App\Entity\Client
                property: email # ou nom_utilisateur, selon votre préférence pour l'authentification

    # Configuration des pare-feux
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_client_provider
            form_login:
                login_path: app_login # Mettez à jour cette route vers votre page de connexion
                check_path: app_login # Mettez à jour cette route pour le traitement du formulaire de connexion
            logout:
                path: app_logout # Mettez à jour cette route pour la déconnexion
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path:     /
                always_remember_me: true
            custom_authenticator: App\Security\UserAuthenticator
            entry_point: 'form_login'

    # Restriction d'accès par rôles
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN } # Exemple d'accès restreint à l'admin
         # Ajoutez d'autres restrictions ici si nécessaire
